// AUTO-GENERATED BY tools/schemagen — DO NOT EDIT BY HAND.
// Source: packages/schema/compgit.schema.json. Run `pnpm gen:schema` to regenerate.

import Foundation

/// GitHub's discretised intensity bucket for a contribution day.
public enum ContributionLevel: String, Codable, CaseIterable, Sendable {
    case none = "NONE"
    case firstQuartile = "FIRST_QUARTILE"
    case secondQuartile = "SECOND_QUARTILE"
    case thirdQuartile = "THIRD_QUARTILE"
    case fourthQuartile = "FOURTH_QUARTILE"
}

/// One day on a GitHub user's contribution calendar.
public struct ContributionDay: Codable, Hashable, Sendable {
    /// Total contributions credited on this date.
    public let contributionCount: Int
    public let contributionLevel: ContributionLevel
    /// ISO-8601 date (YYYY-MM-DD) in the user's GitHub-configured timezone.
    public let date: String
    public init(contributionCount: Int, contributionLevel: ContributionLevel, date: String) {
        self.contributionCount = contributionCount
        self.contributionLevel = contributionLevel
        self.date = date
    }
}

/// Normalised snapshot of a GitHub user's contribution calendar over a fixed window.
public struct ContributionsCollection: Codable, Hashable, Sendable {
    /// Flattened daily contributions, ordered oldest-first.
    public let days: [ContributionDay]
    /// When the client received this snapshot, ISO-8601 UTC string.
    public let fetchedAt: String
    /// Inclusive lower bound, ISO-8601 UTC string.
    public let from: String
    public let login: String
    /// Inclusive upper bound, ISO-8601 UTC string.
    public let to: String
    public let totalContributions: Int
    public init(days: [ContributionDay], fetchedAt: String, from: String, login: String, to: String, totalContributions: Int) {
        self.days = days
        self.fetchedAt = fetchedAt
        self.from = from
        self.login = login
        self.to = to
        self.totalContributions = totalContributions
    }
}

/// A GitHub user the device owner is tracking for comparison.
public struct FollowedDeveloper: Codable, Hashable, Sendable {
    /// When this developer was added, ISO-8601 UTC string.
    public let addedAt: String
    public let avatarUrl: String?
    /// Optional human-readable label shown in the compare tab.
    public let displayName: String?
    public let login: String
    public init(addedAt: String, avatarUrl: String? = nil, displayName: String? = nil, login: String) {
        self.addedAt = addedAt
        self.avatarUrl = avatarUrl
        self.displayName = displayName
        self.login = login
    }
}
