import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Canonical JSON Schema → TypeScript + Swift models.
 *
 * Purpose-built for compgit's small `definitions` set. Uses no codegen library
 * because quicktype deduplicates poorly across sibling $refs in this shape
 * and we want predictable, diffable output.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..', '..');
const SCHEMA_FILE = join(ROOT, 'packages', 'schema', 'compgit.schema.json');
const TS_OUT = join(ROOT, 'packages', 'shared-ts', 'src', 'generated.ts');
const SWIFT_OUT = join(
  ROOT,
  'packages',
  'shared-swift',
  'Sources',
  'CompgitSchema',
  'Generated.swift',
);

const BANNER_TS = `// AUTO-GENERATED BY tools/schemagen — DO NOT EDIT BY HAND.
// Source: packages/schema/compgit.schema.json. Run \`pnpm gen:schema\` to regenerate.
`;
const BANNER_SWIFT = `// AUTO-GENERATED BY tools/schemagen — DO NOT EDIT BY HAND.
// Source: packages/schema/compgit.schema.json. Run \`pnpm gen:schema\` to regenerate.

import Foundation
`;

type JsonSchemaNode = {
  type?: string | string[];
  title?: string;
  description?: string;
  enum?: string[];
  pattern?: string;
  minimum?: number;
  format?: string;
  required?: string[];
  properties?: Record<string, JsonSchemaNode>;
  items?: JsonSchemaNode;
  $ref?: string;
  additionalProperties?: boolean | JsonSchemaNode;
};

type RootSchema = {
  definitions: Record<string, JsonSchemaNode>;
};

function refName(ref: string): string {
  const match = /#\/definitions\/([A-Za-z0-9]+)$/.exec(ref);
  if (!match) throw new Error(`unsupported $ref: ${ref}`);
  return match[1]!;
}

function tsType(node: JsonSchemaNode): string {
  if (node.$ref) return refName(node.$ref);
  if (node.enum && node.type === 'string') {
    return node.enum.map((v) => JSON.stringify(v)).join(' | ');
  }
  if (Array.isArray(node.type)) {
    return node.type.map((t) => tsType({ ...node, type: t })).join(' | ');
  }
  switch (node.type) {
    case 'string':
      return 'string';
    case 'integer':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      if (!node.items) throw new Error('array without items');
      return `${tsType(node.items)}[]`;
    default:
      throw new Error(`unhandled TS type: ${String(node.type)}`);
  }
}

function swiftType(node: JsonSchemaNode): string {
  if (node.$ref) return refName(node.$ref);
  switch (node.type) {
    case 'string':
      return 'String';
    case 'integer':
      return 'Int';
    case 'number':
      return 'Double';
    case 'boolean':
      return 'Bool';
    case 'array':
      if (!node.items) throw new Error('array without items');
      return `[${swiftType(node.items)}]`;
    default:
      throw new Error(`unhandled Swift type: ${String(node.type)}`);
  }
}

function emitDocComment(desc: string | undefined, indent: string): string {
  if (!desc) return '';
  return `${indent}/** ${desc} */\n`;
}

function emitSwiftDocComment(desc: string | undefined, indent: string): string {
  if (!desc) return '';
  return `${indent}/// ${desc}\n`;
}

function emitTsDefinition(name: string, node: JsonSchemaNode): string {
  if (node.enum && node.type === 'string') {
    const union = node.enum.map((v) => JSON.stringify(v)).join(' | ');
    return `${emitDocComment(node.description, '')}export type ${name} = ${union};`;
  }
  if (node.type !== 'object' || !node.properties) {
    throw new Error(`unsupported definition ${name}`);
  }
  const required = new Set(node.required ?? []);
  const lines: string[] = [];
  lines.push(emitDocComment(node.description, '').trimEnd());
  lines.push(`export interface ${name} {`);
  const propNames = Object.keys(node.properties).sort();
  for (const propName of propNames) {
    const prop = node.properties[propName]!;
    const optional = required.has(propName) ? '' : '?';
    lines.push(emitDocComment(prop.description, '  ').trimEnd());
    lines.push(`  ${propName}${optional}: ${tsType(prop)};`);
  }
  lines.push('}');
  return lines.filter((line) => line !== '').join('\n');
}

function emitSwiftDefinition(name: string, node: JsonSchemaNode): string {
  if (node.enum && node.type === 'string') {
    const cases = node.enum.map((v) => `    case ${camelCase(v)} = "${v}"`).join('\n');
    return [
      emitSwiftDocComment(node.description, '').trimEnd(),
      `public enum ${name}: String, Codable, CaseIterable, Sendable {`,
      cases,
      '}',
    ]
      .filter((line) => line !== '')
      .join('\n');
  }
  if (node.type !== 'object' || !node.properties) {
    throw new Error(`unsupported definition ${name}`);
  }
  const required = new Set(node.required ?? []);
  const lines: string[] = [];
  lines.push(emitSwiftDocComment(node.description, '').trimEnd());
  lines.push(`public struct ${name}: Codable, Hashable, Sendable {`);
  const propNames = Object.keys(node.properties).sort();
  const initArgs: string[] = [];
  const initBody: string[] = [];
  for (const propName of propNames) {
    const prop = node.properties[propName]!;
    const isOptional = !required.has(propName);
    const swiftT = swiftType(prop);
    const finalType = isOptional ? `${swiftT}?` : swiftT;
    lines.push(emitSwiftDocComment(prop.description, '    ').trimEnd());
    lines.push(`    public let ${propName}: ${finalType}`);
    initArgs.push(`${propName}: ${finalType}${isOptional ? ' = nil' : ''}`);
    initBody.push(`        self.${propName} = ${propName}`);
  }
  lines.push('');
  lines.push(`    public init(${initArgs.join(', ')}) {`);
  lines.push(initBody.join('\n'));
  lines.push('    }');
  lines.push('}');
  return lines.filter((line) => line !== '').join('\n');
}

function camelCase(value: string): string {
  const parts = value.toLowerCase().split('_');
  return parts
    .map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');
}

function orderedDefinitions(root: RootSchema): Array<[string, JsonSchemaNode]> {
  // Emit enums first (leaf types), then objects. Within each group, sort alphabetically for deterministic diffs.
  const entries = Object.entries(root.definitions);
  const enums = entries.filter(([, node]) => node.enum).sort(([a], [b]) => a.localeCompare(b));
  const objects = entries.filter(([, node]) => !node.enum).sort(([a], [b]) => a.localeCompare(b));
  return [...enums, ...objects];
}

async function main(): Promise<void> {
  const raw = await readFile(SCHEMA_FILE, 'utf8');
  const root = JSON.parse(raw) as RootSchema;
  if (!root.definitions) {
    throw new Error('compgit.schema.json must have a top-level "definitions" block');
  }
  const ordered = orderedDefinitions(root);

  const tsBody = ordered.map(([name, node]) => emitTsDefinition(name, node)).join('\n\n');
  const swiftBody = ordered.map(([name, node]) => emitSwiftDefinition(name, node)).join('\n\n');

  await mkdir(dirname(TS_OUT), { recursive: true });
  await mkdir(dirname(SWIFT_OUT), { recursive: true });
  await writeFile(TS_OUT, `${BANNER_TS}\n${tsBody}\n`, 'utf8');
  await writeFile(SWIFT_OUT, `${BANNER_SWIFT}\n${swiftBody}\n`, 'utf8');

  process.stdout.write(`wrote ${TS_OUT}\n`);
  process.stdout.write(`wrote ${SWIFT_OUT}\n`);
}

main().catch((err: unknown) => {
  process.stderr.write(`${err instanceof Error ? (err.stack ?? err.message) : String(err)}\n`);
  process.exit(1);
});
