// AUTO-GENERATED BY tools/schemagen — DO NOT EDIT BY HAND.
// Source: packages/schema/compgit.schema.json. Run `pnpm gen:schema` to regenerate.

/** GitHub's discretised intensity bucket for a contribution day. */
export type ContributionLevel = "NONE" | "FIRST_QUARTILE" | "SECOND_QUARTILE" | "THIRD_QUARTILE" | "FOURTH_QUARTILE";

/** One day on a GitHub user's contribution calendar. */
export interface ContributionDay {
  /** Total contributions credited on this date. */
  contributionCount: number;
  contributionLevel: ContributionLevel;
  /** ISO-8601 date (YYYY-MM-DD) in the user's GitHub-configured timezone. */
  date: string;
}

/** Normalised snapshot of a GitHub user's contribution calendar over a fixed window. */
export interface ContributionsCollection {
  /** Flattened daily contributions, ordered oldest-first. */
  days: ContributionDay[];
  /** When the client received this snapshot, ISO-8601 UTC string. */
  fetchedAt: string;
  /** Inclusive lower bound, ISO-8601 UTC string. */
  from: string;
  login: string;
  /** Inclusive upper bound, ISO-8601 UTC string. */
  to: string;
  totalContributions: number;
}

/** A GitHub user the device owner is tracking for comparison. */
export interface FollowedDeveloper {
  /** When this developer was added, ISO-8601 UTC string. */
  addedAt: string;
  avatarUrl?: string;
  /** Optional human-readable label shown in the compare tab. */
  displayName?: string;
  login: string;
}
